/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Robi
 * Created: 13-mag-2016
 */

create database ammdb;

create table prodotti (
    cod INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    tipo VARCHAR(128),
    pezzi INTEGER,
    prezzo FLOAT,
    imgurl VARCHAR(128)
);

create table utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo BOOLEAN,
    username VARCHAR(128),
    password VARCHAR(128),
    nome VARCHAR(128),
    cognome VARCHAR(128),
    saldo double
);

insert into prodotti(nome,tipo,pezzi,prezzo,imgurl)
values ('Nexus4','Smartphone',12,200.0,'nexus4.png'),
('Nexus5','Smartphone',93,250.0,'nexus5.jpg'),
('Nexus6','Smartphone',134,300.0,'nexus6.jpg'),
('Nexus5X','Smartphone',350,400.0,'nexus5x.jpg'),
('Nexus6P','Smartphone',450,500.0,'nexus6p.jpg');

insert into utenti(tipo,username,password,nome,cognome,saldo)
values (false,'robertospiga','1234','Roberto','Spiga',400.0),
(false,'nicolabissiri','1234','Nicola','Bissiri',250.0),
(true,'alessiospiga','1234','Alessio','Spiga',0.0),
(true,'paolocorpino','1234','Paolo','Corpino',0.0);

create table prodotti_utenti (
    codProdotto INTEGER,
    idUtente INTEGER,
    FOREIGN KEY (codProdotto) REFERENCES prodotti(cod),
    FOREIGN KEY (idUtente) REFERENCES utenti(id),
    PRIMARY KEY (codProdotto,idUtente)
);

insert into prodotti_utenti(codProdotto,idUtente)
values (1,1),
(2,1),
(3,2),
(5,2),
(1,3),
(2,3),
(3,4),
(4,4);



